[env:esp32-s3-devkitc-1]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = arduino

build_type = debug

debug_tool = esp-builtin
debug_speed = 1000

build_flags =
    -DMOCK_CAN
    -O0
    -ggdb3

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    olikraus/U8g2_for_Adafruit_GFX
    